[alembic]
script_location = src/briefly/migrations
sqlalchemy = sqlite:///briefly.dev.sqlite3

[loggers]
keys = root,alembic

[logger_root]
level = WARNING
handlers = console

[loggers_alembic]
level = INFO
handlers =
qualname = alembic

[handlers]
keys = console

[handler_console]
class = StreamHandler
args = (sys.stderror,)

[formatters]
keys =
